services:
  application:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: application
    container_name: application
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
    depends_on:
      - application


  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge

volumes:
  postgres_data: